version: 1
tasks:
  - workerType: docker-worker
    worker:
      docker:
        image: mozillasecurity/ci-test:latest  # Firefox test image
        command:
          - pytest
          - tests/test_home_page.py
        artifacts:
          "public/test_results":
            type: directory
            path: /home/worker/test_results
      environment:
        GECKODRIVER_PATH: /usr/local/bin/geckodriver
      maxRunTime: 1800
    metadata:
      name: "Run tests on Firefox"
      description: "Run Selenium tests using Firefox"
      owner: "mobm93@hotmail.com"
      source: https://github.com/mobm93/mobm93.github.io
    routes:
      - "github.push"  # Trigger on pushes to GitHub
    scopes:
      - "queue:run-task"
    retries: 3
