version: 1
tasks:
  - workerType: docker-worker
    provisionerId: "aws-provisioner-v1"
    payload:
      image: "mozillasecurity/ci-test:latest"
      command:
        - pytest
        - tests/test_home_page.py
      maxRunTime: 1800
    metadata:
      name: "Run tests on Firefox"
      description: "Run Selenium tests using Firefox"
      owner: "mobm93@hotmail.com"
      source: https://github.com/mobm93/mobm93.github.io
    scopes:
      - "queue:run-task"
    routes:
      - "github.push"
    retries: 3
    deadline: "2024-12-04T00:00:00Z"
