version: 1
triggers:
  github:
    type: "github"
    parameters:
      github:
        repository: "mobm93/mobm93.github.io"
        event: "push"
        branch: "master"
    tasks:
      - taskcluster:
          taskId: "test-firefox"
          metadata:
            name: "Run tests on Firefox"
          taskDefinition:
            version: 1
            task: 
              name: "Run Firefox tests"
              taskcluster:
                taskId: "test-firefox"
